services:
  mailpit-chatbot:
    image: axllent/mailpit:latest
    container_name: mailpit-chatbot
    <<: [ *base, *servicebase ]
    environment:
      - MP_MAX_MESSAGES=5000
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
      - TZ=America/Sao_Paulo
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rede_proxy"
      - "traefik.http.routers.mailpit-chatbot.service=mailpit-chatbot"
      - "traefik.http.routers.mailpit-chatbot.rule=Host(`mail-chatbot.${DOMAIN}`)"
      - "traefik.http.routers.mailpit-chatbot.entrypoints=websecure"
      - "traefik.http.routers.mailpit-chatbot.tls.certresolver=letsencrypt"
      - "traefik.http.services.mailpit-chatbot.loadbalancer.server.port=8025"
    volumes:
      - mailpit_data:/data

volumes:
  mailpit_data: