services:
  docops:
    image: or4cu1o/docops:beta
    container_name: docops-chatbot
    restart: unless-stopped
    environment:
      - DOCOPS_USER=admin
      - DOCOPS_PASS=admin
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    networks:
      - rede_proxy
